# Generated by Django 4.2.3 on 2023-07-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='prod_available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='prod_stock',
        ),
    ]
